### PR TITLE
tests: remove accidentally-committed package-lock.json

### PR DESCRIPTION
**Pull request by jordigh**
This file doesn't belong here, because we run versioned tests against the latest semver matches. Something has recently changed in Node 14 that is incompatible with this file, so let's just remove it.

## Proposed Release Notes

* Removed accidentally-committed `package-lock.json` in versioned tests.

### CODE REVIEW

**Review by bizob2828 — COMMENTED** [review]
should we add a .gitignore entry to prevent this from happening in future?

**Comment by jordigh** [comment]
> should we add a .gitignore entry to prevent this from happening in future?

Ah, good idea, added it.

**Comment by bizob2828** [comment]
FWIW removing this doesn't do anything.  package-lock is only used when running `npm ci` which does not happen with the versioned test runner.  You called out some failures in node-newrelic but they are no longer failing, we can merge this but it's not fixing anything aside from a mistake by a dev

**Comment by jordigh** [comment]
I think it is being used, accidentally, as it's mentioned in the failing build log for the main repo. I was able to locally reproduce the test failure on node 14. It went away after I deleted this file.

**Comment by bizob2828** [comment]
> I think it is being used, accidentally, as it's mentioned in the failing build log for the main repo. I was able to locally reproduce the test failure on node 14. It went away after I deleted this file.

I don't see it being accidentally used, that's just a warning
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

I just ran [main](https://github.com/newrelic/newrelic-node-nextjs/actions/runs/4379307533) on this repo and it's green. We can totally merge this but it's not fixing what you think it is..

**Review by bizob2828 — APPROVED** [review]

**Pull request merged**
